# ♠️🌿🎸🧵 termux-init — core shell config (00-core.sh)
# Owned by @gerico1007/termux-init. Reinstalls overwrite this file.
# Do not hand-edit; put your own customizations in ~/.bashrc.d/99-local.sh.

# ── PATH ────────────────────────────────────────────────────────────
export PATH="$HOME/.local/bin:$HOME/bin:$PATH"

# ── Termux quirks ───────────────────────────────────────────────────
# Node/claude-code expect a writable TMPDIR outside /data/data/.../usr/tmp
export TMPDIR="$HOME/tmp"
mkdir -p "$TMPDIR"

# Claude Code: don't auto-update (we manage via npm)
export DISABLE_AUTOUPDATER=1

# Claude Code alias: writable TMPDIR + skip interactive permission prompts.
# ⚠ SECURITY NOTE: --dangerously-skip-permissions runs every tool call without
# asking. Intentional for Forest devices (Jerry's own phones, fast workflow),
# but means any prompt that reaches Claude executes immediately. Drop the flag
# (`unalias claude`) before pasting in untrusted prompts from third parties.
alias claude="TMPDIR=\"$HOME/tmp\" claude --dangerously-skip-permissions"

# ── Local secrets ───────────────────────────────────────────────────
# Auto-source ~/.env if it exists (kv pairs become env vars)
[ -f "$HOME/.env" ] && set -a && . "$HOME/.env" && set +a

# ── Forest of Gerico — mesh status helper ───────────────────────────
# Asks the forest-registry for the current node roster (including platform +
# ssh_port), then probes each node with a real SSH handshake. iOS nodes (no
# sshd) are labeled accordingly. Falls back to a hardcoded roster if the
# registry is unreachable.
forest-status() {
  local registry="${FOREST_REGISTRY_URL:-http://eury.ferret-harmonic.ts.net:8771}"
  local nodes_json
  if command -v jq >/dev/null 2>&1 \
      && nodes_json=$(curl -sf --max-time 3 "$registry/nodes" 2>/dev/null); then
    echo "$nodes_json" | jq -r '.nodes[] | "\(.hostname)\t\(.platform // "?")\t\(.ssh_port // "-")"' \
      | while IFS=$'\t' read -r host platform port; do
        printf "%-10s [%-6s] " "$host" "$platform"
        if [ "$port" = "-" ] || [ -z "$port" ]; then
          echo "no sshd"
        elif ssh -o BatchMode=yes -o ConnectTimeout=3 -o StrictHostKeyChecking=accept-new \
                "$host" true 2>/dev/null; then
          echo "ssh ok"
        else
          echo "ssh unreachable"
        fi
      done
  else
    echo "⚠ registry $registry unreachable; probing fallback roster via SSH config"
    local fallback="eury larix ilex tilia abies"
    for n in $fallback; do
      printf "%-10s          " "$n"
      ssh -o BatchMode=yes -o ConnectTimeout=3 "$n" true 2>/dev/null \
        && echo "ssh ok" || echo "ssh unreachable"
    done
  fi
}

# ── Eury connection — ngrok backup (Tailscale primary) ──────────────
# Use only when Tailscale is unreachable. eury-config asks for ngrok number + port,
# writes ~/.eury_config and an ssh-config Host block.
EURY_CONFIG_FILE="$HOME/.eury_config"

eury-config() {
  read -p "Ngrok number: " _num
  read -p "Port: " _port
  read -p "User [gmusic]: " _user
  _user=${_user:-gmusic}
  _host="${_num}.tcp.ngrok.io"

  cat > "$EURY_CONFIG_FILE" <<EOF
# Eury ngrok-fallback configuration (auto-generated by eury-config)
export _host="$_host"
export _port="$_port"
export _user="$_user"
EOF

  local ssh_config="$HOME/.ssh/config"
  mkdir -p "$HOME/.ssh"
  if [ ! -f "$ssh_config" ] || ! grep -q "^Host eury$" "$ssh_config"; then
    cat >> "$ssh_config" <<SSHEOF

Host eury
    HostName $_host
    Port $_port
    User $_user
    IdentityFile ~/.ssh/id_ed25519
SSHEOF
    chmod 600 "$ssh_config"
  else
    # Rewrite the existing `Host eury` block in place. The terminator pattern
    # must match ANY new `Host ` line that isn't `Host eury` itself — otherwise
    # sibling blocks like `Host elastic` or `Host eury2` would silently get
    # their HostName/Port/User clobbered too.
    awk -v host="$_host" -v port="$_port" -v user="$_user" '
      /^Host / {
        if ($0 == "Host eury") { in_eury=1 }
        else { in_eury=0 }
      }
      in_eury && /^[[:space:]]*HostName / { $0="    HostName " host; print; next }
      in_eury && /^[[:space:]]*Port /     { $0="    Port "     port; print; next }
      in_eury && /^[[:space:]]*User /     { $0="    User "     user; print; next }
      { print }
    ' "$ssh_config" > "${ssh_config}.tmp" && mv "${ssh_config}.tmp" "$ssh_config"
    chmod 600 "$ssh_config"
  fi

  . "$EURY_CONFIG_FILE"
  echo "✓ Eury ngrok-fallback set: $_user@$_host:$_port"
}

eury() {
  if [ -z "${_host:-}" ] || [ -z "${_port:-}" ]; then
    echo "⚠ Eury ngrok-fallback not configured. Run 'eury-config' first."
    echo "  (Tailscale primary path: ssh gmusic@eury.ferret-harmonic.ts.net)"
    return 1
  fi
  if ! getent hosts "$_host" >/dev/null 2>&1; then
    echo "⚠ Cannot resolve $_host — is the ngrok tunnel up on Eury?"
    return 1
  fi
  local user=${1:-$_user}
  ssh "$user@$_host" -p "$_port"
}

[ -f "$EURY_CONFIG_FILE" ] && . "$EURY_CONFIG_FILE"

alias gmeury='eury gmusic'
alias sshnyro='eury nyro'
