# ♠️🌿🎸🧵 termux-init — core shell config (00-core.sh)
# Owned by @gerico1007/termux-init. Reinstalls overwrite this file.
# Do not hand-edit; put your own customizations in ~/.bashrc.d/99-local.sh.

# ── PATH ────────────────────────────────────────────────────────────
export PATH="$HOME/.local/bin:$HOME/bin:$PATH"

# ── Termux quirks ───────────────────────────────────────────────────
# Node/claude-code expect a writable TMPDIR outside /data/data/.../usr/tmp
export TMPDIR="$HOME/tmp"
mkdir -p "$TMPDIR"

# Claude Code: don't auto-update (we manage via npm)
export DISABLE_AUTOUPDATER=1

# Claude Code alias: writable TMPDIR + skip interactive permission prompts.
# ⚠ SECURITY NOTE: --dangerously-skip-permissions runs every tool call without
# asking. Intentional for Forest devices (Jerry's own phones, fast workflow),
# but means any prompt that reaches Claude executes immediately. Drop the flag
# (`unalias claude`) before pasting in untrusted prompts from third parties.
alias claude="TMPDIR=\"$HOME/tmp\" claude --dangerously-skip-permissions"

# ── Local secrets ───────────────────────────────────────────────────
# Auto-source ~/.env if it exists (kv pairs become env vars)
[ -f "$HOME/.env" ] && set -a && . "$HOME/.env" && set +a

# ── Forest of Gerico — mesh status helper ───────────────────────────
forest-status() {
  local nodes="eury larix ilex tilia abies iroko ginkgo itea"
  for n in $nodes; do
    printf "%-8s " "$n"
    if command -v tailscale >/dev/null 2>&1; then
      tailscale ping -c 1 "$n" 2>/dev/null | grep -E 'pong|timed out|no route' | head -1 || echo "(no response)"
    else
      ping -c 1 -W 2 "$n.ferret-harmonic.ts.net" >/dev/null 2>&1 && echo "reachable" || echo "unreachable"
    fi
  done
}

# ── Eury connection — ngrok backup (Tailscale primary) ──────────────
# Use only when Tailscale is unreachable. eury-config asks for ngrok number + port,
# writes ~/.eury_config and an ssh-config Host block.
EURY_CONFIG_FILE="$HOME/.eury_config"

eury-config() {
  read -p "Ngrok number: " _num
  read -p "Port: " _port
  read -p "User [gmusic]: " _user
  _user=${_user:-gmusic}
  _host="${_num}.tcp.ngrok.io"

  cat > "$EURY_CONFIG_FILE" <<EOF
# Eury ngrok-fallback configuration (auto-generated by eury-config)
export _host="$_host"
export _port="$_port"
export _user="$_user"
EOF

  local ssh_config="$HOME/.ssh/config"
  mkdir -p "$HOME/.ssh"
  if [ ! -f "$ssh_config" ] || ! grep -q "^Host eury$" "$ssh_config"; then
    cat >> "$ssh_config" <<SSHEOF

Host eury
    HostName $_host
    Port $_port
    User $_user
    IdentityFile ~/.ssh/id_ed25519
SSHEOF
    chmod 600 "$ssh_config"
  else
    # Rewrite the existing `Host eury` block in place. The terminator pattern
    # must match ANY new `Host ` line that isn't `Host eury` itself — otherwise
    # sibling blocks like `Host elastic` or `Host eury2` would silently get
    # their HostName/Port/User clobbered too.
    awk -v host="$_host" -v port="$_port" -v user="$_user" '
      /^Host / {
        if ($0 == "Host eury") { in_eury=1 }
        else { in_eury=0 }
      }
      in_eury && /^[[:space:]]*HostName / { $0="    HostName " host; print; next }
      in_eury && /^[[:space:]]*Port /     { $0="    Port "     port; print; next }
      in_eury && /^[[:space:]]*User /     { $0="    User "     user; print; next }
      { print }
    ' "$ssh_config" > "${ssh_config}.tmp" && mv "${ssh_config}.tmp" "$ssh_config"
    chmod 600 "$ssh_config"
  fi

  . "$EURY_CONFIG_FILE"
  echo "✓ Eury ngrok-fallback set: $_user@$_host:$_port"
}

eury() {
  if [ -z "${_host:-}" ] || [ -z "${_port:-}" ]; then
    echo "⚠ Eury ngrok-fallback not configured. Run 'eury-config' first."
    echo "  (Tailscale primary path: ssh gmusic@eury.ferret-harmonic.ts.net)"
    return 1
  fi
  if ! getent hosts "$_host" >/dev/null 2>&1; then
    echo "⚠ Cannot resolve $_host — is the ngrok tunnel up on Eury?"
    return 1
  fi
  local user=${1:-$_user}
  ssh "$user@$_host" -p "$_port"
}

[ -f "$EURY_CONFIG_FILE" ] && . "$EURY_CONFIG_FILE"

alias gmeury='eury gmusic'
alias sshnyro='eury nyro'
